### ISSUE TITLE
Average and plot

### ISSUE THREAD

**Issue by ktavabi** [BioMag/meg_scripts#1]
`python chpi_weighted_average.py Fc_12mo_104_raw.fif --plot_snr True` doesn't plot cHPI snr time course.

**Comment by jjnurminen** [comment]
It works for me. I would guess it's some kind of matplotlib backend issue.
If you save the following into a plot_test.py and run it, do you get a figure?

```
import matplotlib.pyplot as plt
plt.plot([1, 2, 3, 4, 5])
plt.show()
```

**Comment by ktavabi** [comment]
the above example works for me when I do plt.show(block=True) which hangs everything until figure window is closed. I know there were many e.g., of this sort of behavior in mne-python visualizations but I can't recall how they got around it. This is not a big deal, we'll deal with it after integration.
