### ISSUE TITLE
Averaging script on phantom data fails

### ISSUE THREAD

**Issue by ktavabi** [BioMag/meg_scripts#2]
`python chpi_weighted_average.py chpi_snr_test_raw_tsss_mc.fif` fails with a `ValueError`:

> Processing category 32 : Dipole 32
> Loading epochs for cHPI SNR...
> Traceback (most recent call last):
>   File "chpi_weighted_average.py", line 165, in <module>
>     chpi_epochs = mne.Epochs(raw_chpi, events, {catname: id}, tmin=epoch_start, tmax=epoch_end, baseline=None, picks=picks, preload=True, verbose=verbose)
>   File "<string>", line 2, in **init**
>   File "/home/ktavabi/Projects/mne-python/mne/utils.py", line 683, in verbose
>     return function(_args, *_kwargs)
>   File "/home/ktavabi/Projects/mne-python/mne/epochs.py", line 1794, in **init**
>     on_missing=on_missing, preload_at_end=preload, verbose=verbose)
>   File "/home/ktavabi/Projects/mne-python/mne/epochs.py", line 196, in **init**
>     raise ValueError(msg)
> ValueError: No matching events found for Dipole 32 (event id 32)

**Comment by jjnurminen** [comment]
@kambysese I would guess that Category #32 is activated in the acquisition, but there are no events in the data that correspond to it. Please try the latest commit.

**Comment by ktavabi** [comment]
@jjnurminen Actually it looks like Category #7 is activated, I figured it out by:

```
raw_sss=['chpi_snr_test_raw_tsss_mc.fif']
for ii in range(1, len(ap.categories)+1):
    cond = ap.get_condition(raw_sss, ap['Dipole %d' % ii], stim_channel='STI201')
    print(cond['events'].shape[0] > 0)
cond = ap.get_condition(raw_sss, ap['Dipole 7'], stim_channel='STI201')
```

Latest commit resolves `ValueError` but fails to find events for any of the (32) conditions, and fails to write out a file.

**Comment by jjnurminen** [comment]
@kambysese Your events are on stim channel STI201 (as is normal for phantom data). I will add a switch to change the stim channel asap.
For some reason, all 32 averaging categories are active, but there are actual events only for category #7.

**Comment by jjnurminen** [comment]
Try `--stim_channel STI201` with latest commit
It also supports artifact rejection with `--reject`. Rejection settings are read from data acquisition.

**Comment by ktavabi** [comment]
Are you referring to [f623b55](https://github.com/BioMag/meg_scripts/blob/master/python/chpi_weighted_average.py)? I don't see `--stim_channel` arg in the chages; `chpi_weighted_average.py input.fif --stim_channel STI201` returns with _unrecognized arguments_

**Comment by jjnurminen** [comment]
@kambysese Sorry, the fix was on another branch, which is now merged into master. Please try again.

**Comment by ktavabi** [comment]
@jjnurminen still not merged into `master` but change in `reject` works as expected :+1:

**Comment by jjnurminen** [comment]
@kambysese I'm a bit puzzled. It shows up in master, at least for me?

**Comment by ktavabi** [comment]
Looks like It's gone through by now; I probably got a bit over zealous and tried with master before the merge was complete. Thanks.

**Comment by jjnurminen** [comment]
OK! Glad to hear it works for you now.
