### ISSUE TITLE
Weighted epochs inedexing error

### ISSUE THREAD

**Issue by ktavabi** [BioMag/meg_scripts#4]
@jjnurminen [ln228](https://github.com/BioMag/meg_scripts/blob/master/python/chpi_weighted_average.py#L228) throws an `IndexError` b/c `len(eps_ok)` > `w_snr.shape` I think that `epochs.load_data()` in `chpi_snr_epochs` drops bad e.g., TOO SHORT epochs by default.

**Comment by jjnurminen** [comment]
I cannot reproduce this with my own data. Can you send a file which triggers the bug?

**Comment by ktavabi** [comment]
I hit this bug using the phantom data linked from my dropbox in #5.

**Comment by jjnurminen** [comment]
Still cannot reproduce, i.e.
`python python/chpi_weighted_average.py ~/Downloads/phantom_moving_dipole7_raw.fif --stim_channel STI201`

doesn't throw any errors and produces an average file.

Can you specify more exactly how you hit this bug?

**Comment by ktavabi** [comment]
Things are looking really good. Looks like everything was due to my using the wrong raw file to generate weights and evoked file.
