### ISSUE TITLE
How are weights computed

### ISSUE THREAD

**Issue by ktavabi** [BioMag/meg_scripts#5]
@jjnurminen hoping you can help me better understand how weights are calculated. @staulu and I are trying to understand the correspondence between weights as a function of cHPI SNR and/or distance of head from the dewar. To that end I recorded a short phantom recording where I gradually moved the phantom out (i.e., down and froward) out of the dewar. Figure below shows the position and rotation data for phantom.

![phantom_moving_dipole7_raw_pos](https://cloud.githubusercontent.com/assets/4381290/20732339/1c97e5e8-b643-11e6-9146-87cc72c739d5.png)

Below is the corresponding cHPI SNR for the moving phantom recording:
![phantom_moving_dipole7_raw_chpisnr](https://cloud.githubusercontent.com/assets/4381290/20732390/58e3218e-b643-11e6-8a80-f6562644ea5c.png)

Assuming that the magnitude of weights should positively correspond with epochs where the phantom was closer to the top of the dewar i.e., higher snr. Then I expect weights:
`w_snr = chpi_snr_epochs(chpi_epochs, n_lineharm=2, channels='grad', hpi_coil='median')`
plotted as function of time to be positively skewed i.e., higher weights towards beginning of the recording in this case; however I am seeing...

![phantom_moving_dipole7_raw_weights](https://cloud.githubusercontent.com/assets/4381290/20734197/b44aab2e-b64c-11e6-8d31-4f610f7f7fdc.png)

So my first question is whether `w_snr` is the weights? If yes, then what kind of correspondence would you expect between weights and epochs considering the time-course of the cHPI SNR?

FYI below is the cHPI SNR and weights figures for a completely stationary phantom, where I would expect equal/stable weights for the greater duration of the recording

![phantom_station_dipole7_raw_chpisnr](https://cloud.githubusercontent.com/assets/4381290/20734237/0bb0a062-b64d-11e6-9b03-071deb55b384.png)

![phantom_station_dipole7_raw_weights](https://cloud.githubusercontent.com/assets/4381290/20734243/0f9b2364-b64d-11e6-952e-c66fb10ad7be.png)

**Comment by jjnurminen** [comment]
Hi @kambysese @staulu

`w_snr` is indeed the weights. The x axis is not time though, but the epoch index.

The weights should be correlated with the cHPI SNR plot. However by default, the weighting chooses the coil with median SNR at each time point, which can complicate things a bit. 

In the cases I have investigated, the weights clearly reflect the decreased SNR - this is also seen in your plot, but for some reason the change in weights as the phantom moves is quite small . If you send me the raw phantom data, I could try to investigate what is happening there.

**Comment by ktavabi** [comment]
Strange my edits to this issue have not been updated.
For above figures I converted epoch starting sample points in `epochs.events` to time in order to get the x-axis in units sec. Although this may be a poor representation of the weights, I am still curious as to why the larger weights c. 65-70 s in the moving phantom are not earlier where cHPI SNR is clearly higher. 
The phantom data used to generate plots are [here](https://db.tt/TQPlr19l) and the code I used is [here](https://gist.github.com/kambysese/a1d4d034a5b7eb8798cc4099fbcd45ad).

**Comment by jjnurminen** [comment]
Thanks @kambysese, I will look into it
I'm also trying to work on the mnefun integration of this project as soon as I find the time...

**Comment by ktavabi** [comment]
Thanks @jjnurminen it looks like the latest commit on MEG scripts uses conditions from epochs to compute weighted averages. So I was planning to tinker around with that at my own risk unless otherwise specified?

**Comment by jjnurminen** [comment]
@kambysese Of course you can tinker with it, that's the spirit.
Eventually the mnefun version should take `Epochs` and `Raw`as an input, as we agreed. I'll be travelling for the next week and probably don't have time to finish it before I go.

**Comment by jjnurminen** [comment]
Hi @kambysese 

I just did a quick check using the version in this repo. I ran 
`chpi_weighted_average.py phantom_moving_dipole7_raw.fif --stim_channel STI201 --plot`
(NOTE: I changed the plot to linear scale instead of dB - please fetch latest commit if you want to reproduce the same plot)

and I got the following figure, which looks much more in accordance with the phantom/sensor distance than your plot:

I wonder where the difference comes from?

![figure_1](https://cloud.githubusercontent.com/assets/8491321/20793033/ba2ae4e6-b7cd-11e6-853d-11ce03ce251b.png)

**Comment by ktavabi** [comment]
@jjnurminen if only all bugs were so blatantly operator dependent! I've been working with movement compensated data to compute weights due to a miscommunication re: the data used to compute cHPI SNR and the data to weight. Obviously the cHPI SNR input data is the raw data; and the weights (we intend) to apply to movement compensated data. Now, I assume this work scheme also makes sense to you?

Regarding this issue cc @staulu I can confirm that the weights from the raw data look like the figure above from @jjnurminen and weights from movement compensated data look like above figure I produced earlier.

**Comment by ktavabi** [comment]
@jjnurminen we can & should probably go back to normalized SNR plot.

**Comment by jjnurminen** [comment]
Ok @kambysese, good to hear that it works now.
We can plot normalized weights for sure. However the script was actually plotting dB (logarithm of the weights) which might be misleading.

**Comment by staulu** [comment]
Great! The weights seem to make perfect sense now. I am really interested in seeing what this does to some of our most difficult infant cases.

**Comment by jjnurminen** [comment]
> Obviously the cHPI SNR input data is the raw data; and the weights (we intend) to apply to movement compensated data. Now, I assume this work scheme also makes sense to you?

Just to confirm, that's the intended workflow. You normally have to use unprocessed data to compute the weights, since MaxFilter removes the cHPI signals (not sure whether mne-python does). And typically, the epochs to be averaged come from a tSSS/movement compensated file.
